spring:
  application:
    name: weddy
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console #?? url: localhost:8080/h2-console
  sql:
    init:
      platform: h2
      mode: embedded
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
