spring:
  application:
    name: weddy
  datasource:
    url: jdbc:h2:mem:test
#    url: jdbc:h2:tcp://localhost/~/loginTest //jdbc:h2:tcp://localhost/~/loginTest
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console  # url: localhost:8080/h2-console
  sql:
    init:
      platform: h2
      mode: embedded
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

jwt:
  secret: ${JWT_SECRET}
  access-token-duration: ${JWT_ACCESS_TOKEN_DURATION:31536000000}
  refresh-token-duration: ${JWT_REFRESH_TOKEN_DURATION:31536000000}

authorize:
  uris: "${AUTHORIZE_URIS:/,/home.html,/index.html,/h2-console/**,/css/**,/js/**,/images/**,/swagger-ui/*,/v3/api-docs/**,/auth/**}"
skip:
  uris: "${SKIP_URIS:/,/index.html,/h2,/swagger-ui/*,/v3/api-docs/**,/auth/**}"
cors:
  uris: "${CORS_URIS:http://localhost:3000,https://weddy-oi983a9q6-lawit.vercel.app}"

app:
  login-page-url: ${LOGIN_PAGE_URL:http://localhost:8080}
  home-page-url: ${HOME_PAGE_URL:http://localhost:8080/home.html}


kakao:
  auth:
    client: ${KAKAO_CLIENT_ID}
    redirect: ${KAKAO_REDIRECT_URL:http://localhost:8080/auth/kakao/callback}
    tokenUrl: https://kauth.kakao.com/oauth/token
    userInfoUrl: https://kapi.kakao.com/v2/user/me

logging:
  level:
    root: INFO
    org.swyp.weddy: DEBUG      # 프로젝트 패키지는 DEBUG 레벨로 설정
    org.springframework: DEBUG
    org.mybatis: DEBUG         # MyBatis SQL 로그 확인용
    org.h2.server: DEBUG       # H2 데이터베이스 로그
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %msg%n"
